#!/usr/bin/env bash
# test-template.sh — render the Copier template into a temp dir and validate it.
#
# Usage: ./scripts/test-template.sh <profile>
# Profiles: minimal | web | iac | full
#
# Copier facts this script depends on (verified against copier 9.x):
#   - Without --vcs-ref, copier renders the LATEST TAG, not your working tree.
#   - With --vcs-ref=HEAD on a local path, copier auto-includes dirty AND
#     untracked changes via a throwaway wip commit in a temp clone
#     (DirtyLocalWarning). The real working tree is never touched.
set -euo pipefail

profile="${1:-minimal}"
repo_root="$(cd "$(dirname "$0")/.." && pwd)"
dest="$(mktemp -d -t harmon-init-test-XXXXXX)"
trap 'rm -rf "$dest"' EXIT

have() { command -v "$1" >/dev/null 2>&1; }

# In CI every tool must be present; locally, missing tools downgrade to a skip.
required() {
    if [ -n "${GITHUB_ACTIONS:-}" ]; then
        echo "FAIL: required tool '$1' is not installed in CI" >&2
        return 1
    fi
    echo "SKIP: '$1' not installed — skipping $2"
    return 0
}

fail=0
err() {
    echo "FAIL: $*" >&2
    fail=1
}

# Answers shared by every profile. Side-effectful answers are forced off so
# this is safe to run anywhere (no gh repo create, no iCloud moves).
data_args=(
    --data project_name="Smoke Test"
    --data project_description="Generated by test-template.sh (${profile})"
    --data bunch_add=false
    --data obsidian_project_add=false
    --data github_remote_create=false
    --data github_release_init=false
    --data run_task_install=false
)

case "$profile" in
minimal) ;;
web)
    data_args+=(--data project_type=web-astro)
    ;;
iac)
    data_args+=(--data project_type=iac)
    ;;
full)
    # Maximize conditional coverage: web tooling + terraform + ansible +
    # devcontainer + self-hosted runner labels (exercises actionlint config).
    data_args+=(
        --data project_type=web-astro
        --data include_terraform=true
        --data include_ansible=true
        --data devcontainer=true
        --data ci_runner=self-hosted
    )
    ;;
*)
    echo "Unknown profile: ${profile}" >&2
    exit 2
    ;;
esac

if [ -n "$(git -C "$repo_root" status --porcelain)" ]; then
    echo "NOTE: dirty working tree — copier will include dirty/untracked changes (DirtyLocalWarning)."
fi

echo "Rendering profile '${profile}' into ${dest}"
copier copy --trust --defaults --vcs-ref=HEAD "${data_args[@]}" "$repo_root" "$dest"

cd "$dest"

# ── 1. Generated Taskfile parses ────────────────────────────────────
if [ -f Taskfile.yml ]; then
    if have task; then
        task --list-all >/dev/null || err "generated Taskfile.yml does not parse (task --list-all)"
    else
        required task "Taskfile parse check" || fail=1
    fi
else
    err "no Taskfile.yml generated"
fi

# ── 2. No unrendered Copier variables leaked into output ────────────
# Go-task {{.VAR}} and GitHub Actions ${{ }} are legitimate; copier answer
# variables are not. Check both old-style and v3 custom delimiters.
leaks=$(grep -rEl '\{\{ (project_|author_|organization|repo_url|github_org|current_)|\[\[ (project_|author_|organization|repo_url|github_org|current_)' \
    --exclude-dir=.git . 2>/dev/null || true)
if [ -n "$leaks" ]; then
    err "unrendered template variables found in: ${leaks}"
fi

# ── 3. Rendered workflows are valid (actionlint) ────────────────────
STRICT_WORKFLOWS="${STRICT_WORKFLOWS:-1}"
if [ -d .github/workflows ]; then
    if have actionlint; then
        if ! (actionlint); then
            if [ "$STRICT_WORKFLOWS" = "1" ]; then
                err "actionlint failed on rendered workflows"
            else
                echo "WARN: actionlint failed on rendered workflows (non-blocking until template workflows are rewritten)"
            fi
        fi
    else
        required actionlint "workflow lint" || fail=1
    fi
fi

# ── 4. Rendered YAML is valid (yamllint, errors only) ───────────────
if have yamllint; then
    yamllint --no-warnings . || err "yamllint errors in rendered output"
else
    required yamllint "rendered YAML check" || fail=1
fi

# ── 5. Rendered lefthook config parses ──────────────────────────────
if [ -f lefthook.yml ]; then
    if have lefthook; then
        lefthook dump >/dev/null || err "rendered lefthook.yml does not parse"
    else
        required lefthook "lefthook config check" || fail=1
    fi
fi

# ── 6. Rendered shell scripts pass shellcheck + shfmt ────────────────
shell_files=$(find scripts .devcontainer -name '*.sh' -type f 2>/dev/null | tr '\n' ' ')
if [ -n "$shell_files" ]; then
    if have shellcheck; then
        # shellcheck disable=SC2086
        shellcheck --severity=error $shell_files || err "shellcheck failed on rendered scripts"
    else
        required shellcheck "rendered script lint" || fail=1
    fi
    if have shfmt; then
        # shellcheck disable=SC2086
        shfmt -d $shell_files || err "shfmt failed on rendered scripts"
    fi
fi

# ── 7. Rendered JSON files parse (devcontainer.json is JSONC — skipped) ──
json_fail=0
while IFS= read -r jf; do
    case "$jf" in
    *devcontainer.json) continue ;;
    esac
    if ! python3 -c "import json,sys; json.load(open(sys.argv[1]))" "$jf" 2>/dev/null; then
        err "invalid JSON in rendered file: $jf"
        json_fail=1
    fi
done < <(find . -name '*.json' -not -path './.git/*' -not -path './node_modules/*' 2>/dev/null)
[ "$json_fail" -eq 0 ] && echo "JSON: all rendered .json files parse"

# ── 8. Devcontainer configs are readable by the devcontainers CLI ───
if [ -d .devcontainer ]; then
    if ! have devcontainer || ! docker info >/dev/null 2>&1; then
        echo "SKIP: devcontainer CLI or docker daemon unavailable — skipping devcontainer config check"
    else
        for cfg in .devcontainer/devcontainer.json .devcontainer/dev/devcontainer.json; do
            [ -f "$cfg" ] || continue
            devcontainer read-configuration --workspace-folder . --config "$cfg" >/dev/null ||
                err "devcontainer read-configuration failed for $cfg"
        done
    fi
fi

# ── 9. No secrets in the rendered tree (gitleaks) ───────────────────
if have gitleaks; then
    gitleaks detect --no-banner --redact --no-git --source . || err "gitleaks findings in rendered output"
else
    required gitleaks "secrets scan" || fail=1
fi

if [ "$fail" -ne 0 ]; then
    echo "test-template (${profile}): FAILED" >&2
    exit 1
fi
echo "test-template (${profile}): PASS"
