#!/usr/bin/env bash
# test-template.sh — render the Copier template into a temp dir and validate it.
#
# Usage: ./scripts/test-template.sh <profile>
# Profiles: minimal | web | iac | full | meta
#
# IMPORTANT: files with CONDITIONAL NAMES are never even compiled by jinja
# unless some profile makes the condition true (copier skips files whose
# rendered name is empty). Every [% if ... %]-named file must be covered by
# at least one profile below, or syntax errors in it ship silently.
#
# Copier facts this script depends on (verified against copier 9.x):
#   - Without --vcs-ref, copier renders the LATEST TAG, not your working tree.
#   - With --vcs-ref=HEAD on a local path, copier auto-includes dirty AND
#     untracked changes via a throwaway wip commit in a temp clone
#     (DirtyLocalWarning). The real working tree is never touched.
set -euo pipefail

profile="${1:-minimal}"
repo_root="$(cd "$(dirname "$0")/.." && pwd)"
dest="$(mktemp -d -t harmon-init-test-XXXXXX)"
trap 'rm -rf "$dest"' EXIT

have() { command -v "$1" >/dev/null 2>&1; }

# In CI every tool must be present; locally, missing tools downgrade to a skip.
required() {
    if [ -n "${GITHUB_ACTIONS:-}" ]; then
        echo "FAIL: required tool '$1' is not installed in CI" >&2
        return 1
    fi
    echo "SKIP: '$1' not installed — skipping $2"
    return 0
}

fail=0
err() {
    echo "FAIL: $*" >&2
    fail=1
}

# Answers shared by every profile. Side-effectful answers are forced off so
# this is safe to run anywhere (no gh repo create, no iCloud moves). The meta
# profile re-enables bunch/obsidian but renders with --skip-tasks.
data_args=(
    --data project_name="Smoke Test"
    --data project_description="Generated by test-template.sh (${profile})"
    --data github_remote_create=false
    --data github_release_init=false
    --data run_task_install=false
)
if [ "$profile" != "meta" ]; then
    data_args+=(
        --data bunch_add=false
        --data obsidian_project_add=false
    )
fi

copier_flags=()
case "$profile" in
minimal)
    # Exercise the release-please OFF branch: use_release_please defaults on,
    # so every other profile already covers the ON branch + its
    # conditionally-named release-please files.
    data_args+=(--data use_release_please=false)
    ;;
web)
    data_args+=(--data project_type=web-astro)
    ;;
webapp)
    data_args+=(--data project_type=web-app)
    ;;
iac)
    data_args+=(--data project_type=iac)
    ;;
full)
    # Maximize conditional coverage: web tooling + terraform + ansible +
    # devcontainer + self-hosted runner labels (exercises actionlint config)
    # + an org owner != author (renders project-automation.yml, the org
    # branches of the claude workflows, and the merge_queue ruleset rule)
    # + the GitHub project-management doc (docs/project-management.md).
    data_args+=(
        --data project_type=web-astro
        --data include_terraform=true
        --data include_ansible=true
        --data devcontainer=true
        --data ci_runner=self-hosted
        --data github_org=test-org
        --data project_management=github
    )
    ;;
meta)
    # Covers conditionally-named files the other profiles leave disabled:
    # the Bunch + Obsidian .meta notes, license=private, the web-app
    # (tsc --noEmit) branch, and the Linear project-management doc stub.
    # --skip-tasks because the bunch/obsidian _tasks move files into iCloud /
    # the Obsidian vault — real side effects.
    data_args+=(
        --data project_type=web-app
        --data license=private
        --data bunch_add=true
        --data obsidian_project_add=true
        --data project_management=linear
    )
    copier_flags+=(--skip-tasks)
    ;;
*)
    echo "Unknown profile: ${profile}" >&2
    exit 2
    ;;
esac

if [ -n "$(git -C "$repo_root" status --porcelain)" ]; then
    echo "NOTE: dirty working tree — copier will include dirty/untracked changes (DirtyLocalWarning)."
fi

echo "Rendering profile '${profile}' into ${dest}"
copier copy --trust --defaults --vcs-ref=HEAD "${copier_flags[@]+"${copier_flags[@]}"}" "${data_args[@]}" "$repo_root" "$dest"

cd "$dest"

# --skip-tasks profiles have no `git init` task run; some validators
# (lefthook dump) need a git repo.
if [ ! -d .git ]; then
    git init -q
else
    # _tasks ran: git init must be followed by the initial scaffold commit —
    # gh repo create --push and task release:init both require HEAD to exist.
    git rev-parse HEAD >/dev/null 2>&1 || err "_tasks left the rendered repo without an initial commit"
fi

# ── 0a. Rendered repo passes its OWN file-hygiene gate ──────────────
# The generated project's `task lint:hygiene` (scripts/lint-hygiene.sh) is part
# of its merge gate. Running it here catches defects the other validators miss
# because they live in the SOURCE files, not the rendered structure — e.g. a
# `.jinja` whose whitespace-control strips the trailing newline (the LICENSE
# bug) or a shell script committed without its EOF newline. Pure bash + git, so
# no `task install` is needed; runs against the freshly-rendered tree.
if [ -x scripts/lint-hygiene.sh ]; then
    ./scripts/lint-hygiene.sh || err "rendered output fails its own lint:hygiene gate"
fi

# ── 0. AGENTS.md is canonical; CLAUDE.md/GEMINI.md + copilot-instructions.md
#       symlink to it (copilot's canonical file lives under .github/). ──
if [ ! -f AGENTS.md ]; then
    err "AGENTS.md missing from rendered output"
fi
for link in CLAUDE.md GEMINI.md; do
    if [ ! -L "$link" ] || [ "$(readlink "$link")" != "AGENTS.md" ]; then
        err "$link should be a symlink to AGENTS.md"
    fi
done
if [ ! -L .github/copilot-instructions.md ] ||
    [ "$(readlink .github/copilot-instructions.md)" != "../AGENTS.md" ]; then
    err ".github/copilot-instructions.md should be a symlink to ../AGENTS.md"
fi

# ── 1. Generated Taskfile parses ────────────────────────────────────
if [ -f Taskfile.yml ]; then
    if have task; then
        task --list-all >/dev/null || err "generated Taskfile.yml does not parse (task --list-all)"
    else
        required task "Taskfile parse check" || fail=1
    fi
else
    err "no Taskfile.yml generated"
fi

# ── 2. No unrendered Copier variables leaked into output ────────────
# Go-task {{.VAR}} and GitHub Actions ${{ }} are legitimate; copier answer
# variables are not. Check both old-style and v3 custom delimiters.
leaks=$(grep -rEl '\{\{ (project_|author_|organization|repo_url|github_org|current_)|\[\[ (project_|author_|organization|repo_url|github_org|current_)' \
    --exclude-dir=.git . 2>/dev/null || true)
if [ -n "$leaks" ]; then
    err "unrendered template variables found in: ${leaks}"
fi

# ── 3. Rendered workflows are valid (actionlint) ────────────────────
STRICT_WORKFLOWS="${STRICT_WORKFLOWS:-1}"
if [ -d .github/workflows ]; then
    if have actionlint; then
        # Same exclusion the generated Taskfile's lint:actions uses — the
        # project-automation/claude workflows intentionally single-quote
        # GraphQL queries and jq expressions containing '$var'.
        if ! (SHELLCHECK_OPTS="--exclude=SC2016" actionlint); then
            if [ "$STRICT_WORKFLOWS" = "1" ]; then
                err "actionlint failed on rendered workflows"
            else
                echo "WARN: actionlint failed on rendered workflows (non-blocking until template workflows are rewritten)"
            fi
        fi
    else
        required actionlint "workflow lint" || fail=1
    fi
fi

# ── 3b. Rendered JS/TS/JSON is Prettier-clean (node projects) ────────
# A generated repo runs `prettier --check` in its own lint:prettier; if the
# template's RENDERED output isn't already clean, the consumer's very first
# `task verify` fails (recurring example: jinja-bracketed workflow YAML, now
# handed to yamllint via .prettierignore). Catch that here. Explicit options
# match the shipped prettier-config-standard (singleQuote, no-semi,
# trailing-comma none, width 100) so no config package needs installing; the
# rendered .prettierignore (YAML->yamllint, Markdown->markdownlint) is honored.
if [ -f prettier.config.cjs ] && have npx; then
    if ! npx --yes prettier@3 --no-config --single-quote --no-semi \
        --trailing-comma none --print-width 100 --check . >/dev/null 2>&1; then
        err "rendered output is not Prettier-clean — a consumer's first 'task verify' would fail (run: npx prettier --check . in the render)"
    fi
fi

# ── 3c. Rendered Markdown is markdownlint-clean ─────────────────────
# Markdown is excluded from prettier (.prettierignore hands it to markdownlint),
# and nothing else above covers it — so a rendered .md that breaks a markdownlint
# rule (a jinja emitting a bad heading level, list, or fenced block) ships and
# only fails when a consumer runs `task lint:markdown`. Run markdownlint-cli2 in
# CHECK mode with the same globs as that target — NOT `task lint:markdown`, which
# runs `--fix` (it would mutate the render and mask issues). The rendered
# .markdownlint(.json/.jsonc) config is auto-discovered.
if have npx; then
    if ! md_out=$(npx --yes markdownlint-cli2 '**/*.md' '#.claude/**' '#**/node_modules/**' '#dist/**' '#.worktrees/**' '#**/.terraform/**' '#**/.venv/**' '#**/.task/**' 2>&1); then
        printf '%s\n' "$md_out" >&2
        err "rendered Markdown fails markdownlint"
    fi
else
    required npx "rendered Markdown lint (markdownlint-cli2 via npx)" || fail=1
fi

# ── 4. Rendered YAML is valid (yamllint, errors only) ───────────────
if have yamllint; then
    yamllint --no-warnings . || err "yamllint errors in rendered output"
else
    required yamllint "rendered YAML check" || fail=1
fi

# ── 5. Rendered lefthook config parses ──────────────────────────────
if [ -f lefthook.yml ]; then
    if have lefthook; then
        lefthook dump >/dev/null || err "rendered lefthook.yml does not parse"
    else
        required lefthook "lefthook config check" || fail=1
    fi
fi

# ── 6. Rendered shell scripts pass shellcheck + shfmt ────────────────
shell_files=$(find scripts .devcontainer -name '*.sh' -type f 2>/dev/null | tr '\n' ' ')
if [ -n "$shell_files" ]; then
    if have shellcheck; then
        # shellcheck disable=SC2086
        shellcheck --severity=error $shell_files || err "shellcheck failed on rendered scripts"
    else
        required shellcheck "rendered script lint" || fail=1
    fi
    if have shfmt; then
        # shellcheck disable=SC2086
        shfmt -d $shell_files || err "shfmt failed on rendered scripts"
    fi
    # A rendered script with a shebang must ship executable — else the generated
    # repo's lifecycle hooks / `task` callers can't run it, and repos on the
    # legacy node hygiene-check fail their own lint:hygiene on first commit.
    # Safe to check the on-disk bit here: the render lands on the local FS where
    # this test runs (not a fileMode-losing devcontainer mount).
    for sf in $shell_files; do
        [ "$(head -c 2 "$sf" 2>/dev/null)" = "#!" ] || continue
        [ -x "$sf" ] || err "rendered shell script is not executable: $sf"
    done
fi

# ── 7. Rendered JSON files parse (devcontainer.json is JSONC — skipped) ──
json_fail=0
while IFS= read -r jf; do
    case "$jf" in
    *devcontainer.json) continue ;;
    esac
    if ! python3 -c "import json,sys; json.load(open(sys.argv[1]))" "$jf" 2>/dev/null; then
        err "invalid JSON in rendered file: $jf"
        json_fail=1
    fi
done < <(find . -name '*.json' -not -path './.git/*' -not -path './node_modules/*' 2>/dev/null)
[ "$json_fail" -eq 0 ] && echo "JSON: all rendered .json files parse"

# ── 8. Devcontainer configs are readable by the devcontainers CLI ───
if [ -d .devcontainer ]; then
    if ! have devcontainer || ! docker info >/dev/null 2>&1; then
        echo "SKIP: devcontainer CLI or docker daemon unavailable — skipping devcontainer config check"
    else
        for cfg in .devcontainer/devcontainer.json .devcontainer/dev/devcontainer.json; do
            [ -f "$cfg" ] || continue
            devcontainer read-configuration --workspace-folder . --config "$cfg" >/dev/null ||
                err "devcontainer read-configuration failed for $cfg"
        done
    fi
fi

# ── 9. Meta files rendered when enabled ─────────────────────────────
if [ "$profile" = "meta" ]; then
    [ -f ".meta/Code Project - Smoke Test.bunch" ] || err "Bunch file missing from .meta/"
    [ -f ".meta/Smoke Test.md" ] || err "Obsidian note missing from .meta/"
fi

# ── 9b. docs/project-management.md rendered per project_management answer ──
# Two mutually-exclusive conditional-named source files share the rendered name
# docs/project-management.md; assert the right one lands (and none does when the
# answer is 'none') so a broken filename condition can't ship silently.
case "$profile" in
full) # project_management=github; github_org=test-org (an org repo)
    [ -f docs/project-management.md ] || err "GitHub project-management.md missing from docs/"
    grep -q 'Not planned' docs/project-management.md || err "GitHub project-management.md missing expected content"
    # project_management=github → the project-setup script + task render
    # (shellcheck at step 6 and `task --list-all` at step 1 then validate them)
    [ -f scripts/setup-github-project.sh ] || err "scripts/setup-github-project.sh did not render for project_management=github"
    # org + github → the org issue-fields setup script renders too
    [ -f scripts/setup-github-issue-fields.sh ] || err "scripts/setup-github-issue-fields.sh did not render for github+org"
    ;;
meta) # project_management=linear
    [ -f docs/project-management.md ] || err "Linear project-management.md missing from docs/"
    head -1 docs/project-management.md | grep -qx '# Linear' || err "Linear project-management.md not titled 'Linear'"
    grep -q 'TODO' docs/project-management.md || err "Linear project-management.md missing TODO marker"
    [ ! -f scripts/setup-github-issue-fields.sh ] || err "setup-github-issue-fields.sh rendered but project_management!=github for profile '$profile'"
    ;;
*) # project_management=none — neither the doc nor the project-setup scripts render
    [ ! -f docs/project-management.md ] || err "docs/project-management.md present but project_management=none for profile '$profile'"
    [ ! -f scripts/setup-github-project.sh ] || err "setup-github-project.sh rendered but project_management=none for profile '$profile'"
    [ ! -f scripts/setup-github-issue-fields.sh ] || err "setup-github-issue-fields.sh rendered but project_management=none for profile '$profile'"
    ;;
esac

# ── 10. No secrets in the rendered tree (gitleaks) ──────────────────
if have gitleaks; then
    gitleaks detect --no-banner --redact --no-git --source . || err "gitleaks findings in rendered output"
else
    required gitleaks "secrets scan" || fail=1
fi

# ── 11. web-astro: the shipped toolchain works on a real Astro app ───
# The render ships eslint.config.js + prettier.config.cjs (with prettier-plugin-astro)
# but no app, so nothing above exercises them. Overlay a minimal Astro fixture
# (package.json + a few src files), install, and run the SHIPPED toolchain against
# it -- a broken config, plugin-API bump, or build regression fails HERE instead of
# in every generated site. Tools run via their binaries (not `task check`) so the
# intentionally-unbuilt esbuild/sharp scripts don't gate them and local plugins
# (eslint-plugin-astro, prettier-plugin-astro) resolve.
if [ "$profile" = "web" ] && [ -f eslint.config.js ]; then
    if ! have pnpm; then
        required pnpm "web-astro toolchain validation" || fail=1
    else
        cp -R "$repo_root/tests/fixtures/web-astro/." .
        pnpm install --silent >/dev/null 2>&1 || true
        bin="node_modules/.bin"
        if [ ! -x "$bin/eslint" ] || [ ! -x "$bin/prettier" ] || [ ! -x "$bin/astro" ]; then
            err "web-astro fixture: install did not provide the toolchain (see tests/fixtures/web-astro/package.json)"
        elif ! "$bin/eslint" . >/dev/null 2>&1; then
            "$bin/eslint" . || true
            err "web-astro fixture: ESLint failed"
        elif ! "$bin/prettier" --check . >/dev/null 2>&1; then
            "$bin/prettier" --check . || true
            err "web-astro fixture: prettier --check failed (prettier-plugin-astro)"
        elif ! "$bin/astro" check >/dev/null 2>&1; then
            "$bin/astro" check || true
            err "web-astro fixture: astro check (typecheck) failed"
        elif ! "$bin/astro" build >/dev/null 2>&1; then
            "$bin/astro" build || true
            err "web-astro fixture: astro build failed"
        else
            echo "web-astro: shipped toolchain (ESLint + Prettier/astro + astro check + build) clean on a real app"
        fi
    fi
fi

# ── 12. web-app: the shipped ESLint config lints a real React app ────
# Same idea as the web-astro check above, for the web-app (React) project type.
# eslint-plugin-react is not yet ESLint-10-ready, so the fixture pins ESLint 9.
if [ "$profile" = "webapp" ] && [ -f eslint.config.js ]; then
    if have pnpm; then
        cp -R "$repo_root/tests/fixtures/web-app/." .
        pnpm install --silent >/dev/null 2>&1 || true
        if [ ! -x node_modules/.bin/eslint ]; then
            err "web-app fixture: install did not provide eslint (see tests/fixtures/web-app/package.json)"
        elif ! node_modules/.bin/eslint . >/dev/null 2>&1; then
            node_modules/.bin/eslint . || true
            err "web-app fixture: shipped eslint.config.js failed to lint a real React app"
        else
            echo "web-app: shipped ESLint config lints a real React app cleanly"
        fi
    else
        required pnpm "web-app ESLint validation" || fail=1
    fi
fi

if [ "$fail" -ne 0 ]; then
    echo "test-template (${profile}): FAILED" >&2
    exit 1
fi
echo "test-template (${profile}): PASS"
