#!/usr/bin/env bash
# test-template.sh — render the Copier template into a temp dir and validate it.
#
# Usage: ./scripts/test-template.sh <profile>
# Profiles: minimal | web | webapp | iac | full | meta
#
# IMPORTANT: files with CONDITIONAL NAMES are never even compiled by jinja
# unless some profile makes the condition true (copier skips files whose
# rendered name is empty). Every [% if ... %]-named file must be covered by
# at least one profile below, or syntax errors in it ship silently.
#
# Copier facts this script depends on (verified against copier 9.x):
#   - Without --vcs-ref, copier renders the LATEST TAG, not your working tree.
#   - With --vcs-ref=HEAD on a local path, copier auto-includes dirty AND
#     untracked changes via a throwaway wip commit in a temp clone
#     (DirtyLocalWarning). The real working tree is never touched.
set -euo pipefail

# Git hooks export GIT_DIR/GIT_WORK_TREE (in a linked worktree GIT_DIR points at
# .git/worktrees/<name>). Left set, the rendered project's `git init` re-targets
# the CALLING repo instead of the temp dir and the render never becomes a repo
# (actionlint then fails with "no project was found"). Sanitize unconditionally.
unset GIT_DIR GIT_WORK_TREE GIT_INDEX_FILE

profile="${1:-minimal}"
repo_root="$(cd "$(dirname "$0")/.." && pwd)"
dest="$(mktemp -d -t harmon-init-test-XXXXXX)"
trap 'rm -rf "$dest"' EXIT

have() { command -v "$1" >/dev/null 2>&1; }

# In CI every tool must be present; locally, missing tools downgrade to a skip.
required() {
    if [ -n "${GITHUB_ACTIONS:-}" ]; then
        echo "FAIL: required tool '$1' is not installed in CI" >&2
        return 1
    fi
    echo "SKIP: '$1' not installed — skipping $2"
    return 0
}

fail=0
err() {
    echo "FAIL: $*" >&2
    fail=1
}

# Answers shared by every profile. Side-effectful answers are forced off so
# this is safe to run anywhere (no gh repo create, no iCloud moves). The meta
# profile re-enables bunch/obsidian but renders with --skip-tasks.
data_args=(
    --data project_name="Smoke Test"
    --data project_description="Generated by test-template.sh (${profile})"
    --data github_remote_create=false
    --data github_release_init=false
    --data run_task_install=false
)
if [ "$profile" != "meta" ]; then
    data_args+=(
        --data bunch_add=false
        --data obsidian_project_add=false
    )
fi

copier_flags=()
case "$profile" in
minimal)
    # Exercise the release-please OFF branch: use_release_please defaults on,
    # so every other profile already covers the ON branch + its
    # conditionally-named release-please files.
    data_args+=(--data use_release_please=false)
    # Exercise the skills-sync OFF branch too (profiles whose seeded categories
    # are empty default off; web profiles cover the ON branch).
    data_args+=(--data use_skills_sync=false)
    # Exercise the devcontainer OFF branch (default on -> every other profile
    # covers the ON branch; full also sets it explicitly).
    data_args+=(--data devcontainer=false)
    # Foreman is opt-in; keep the smallest profile explicitly off so its answer
    # remains obvious in this coverage fixture.
    data_args+=(--data use_foreman=false)
    ;;
web)
    data_args+=(--data project_type=web-astro)
    ;;
webapp)
    data_args+=(--data project_type=web-app)
    ;;
iac)
    # Private infrastructure repos may not have GitHub Code Security. Exercise
    # the explicit CodeQL-off branch so they do not render a workflow whose
    # SARIF upload can never succeed.
    data_args+=(
        --data project_type=iac
        --data use_codeql=false
    )
    ;;
full)
    # Maximize conditional coverage: web tooling + terraform + ansible +
    # devcontainer + self-hosted runner labels (exercises actionlint config)
    # + an org owner != author (renders project-automation.yml, the org
    # branches of the claude workflows, and the merge_queue ruleset rule)
    # + the GitHub project-management doc (docs/project-management.md).
    data_args+=(
        --data project_type=web-astro
        --data include_terraform=true
        --data include_ansible=true
        --data use_foreman=true
        --data devcontainer=true
        --data ci_runner=self-hosted
        --data github_org=test-org
        --data project_management=github
    )
    ;;
meta)
    # Covers conditionally-named files the other profiles leave disabled:
    # the Bunch + Obsidian .meta notes, license=private, the web-app
    # (tsc --noEmit) branch, and the Linear project-management doc stub.
    # --skip-tasks because the bunch/obsidian _tasks move files into iCloud /
    # the Obsidian vault — real side effects.
    data_args+=(
        --data project_type=web-app
        --data license=private
        --data bunch_add=true
        --data obsidian_project_add=true
        --data project_management=linear
    )
    copier_flags+=(--skip-tasks)
    ;;
*)
    echo "Unknown profile: ${profile}" >&2
    exit 2
    ;;
esac

if [ -n "$(git -C "$repo_root" status --porcelain)" ]; then
    echo "NOTE: dirty working tree — copier will include dirty/untracked changes (DirtyLocalWarning)."
fi

echo "Rendering profile '${profile}' into ${dest}"
copier copy --trust --defaults --vcs-ref=HEAD "${copier_flags[@]+"${copier_flags[@]}"}" "${data_args[@]}" "$repo_root" "$dest"

cd "$dest"

# --skip-tasks profiles have no `git init` task run; some validators
# (lefthook dump) need a git repo.
if [ ! -d .git ]; then
    git init -q
else
    # _tasks ran: git init must be followed by the initial scaffold commit —
    # gh repo create --push and task release:init both require HEAD to exist.
    git rev-parse HEAD >/dev/null 2>&1 || err "_tasks left the rendered repo without an initial commit"
fi

# ── 0a. Rendered repo passes its OWN file-hygiene gate ──────────────
# The generated project's `task lint:hygiene` (scripts/lint-hygiene.sh) is part
# of its merge gate. Running it here catches defects the other validators miss
# because they live in the SOURCE files, not the rendered structure — e.g. a
# `.jinja` whose whitespace-control strips the trailing newline (the LICENSE
# bug) or a shell script committed without its EOF newline. Pure bash + git, so
# no `task install` is needed; runs against the freshly-rendered tree.
if [ -x scripts/lint-hygiene.sh ]; then
    ./scripts/lint-hygiene.sh || err "rendered output fails its own lint:hygiene gate"
fi

# ── 0. AGENTS.md is canonical; CLAUDE.md/GEMINI.md + copilot-instructions.md
#       symlink to it (copilot's canonical file lives under .github/). ──
if [ ! -f AGENTS.md ]; then
    err "AGENTS.md missing from rendered output"
fi
for link in CLAUDE.md GEMINI.md; do
    if [ ! -L "$link" ] || [ "$(readlink "$link")" != "AGENTS.md" ]; then
        err "$link should be a symlink to AGENTS.md"
    fi
done
if [ ! -L .github/copilot-instructions.md ] ||
    [ "$(readlink .github/copilot-instructions.md)" != "../AGENTS.md" ]; then
    err ".github/copilot-instructions.md should be a symlink to ../AGENTS.md"
fi

# ── 1. Generated Taskfile parses ────────────────────────────────────
if [ -f Taskfile.yml ]; then
    if have task; then
        task --list-all >/dev/null || err "generated Taskfile.yml does not parse (task --list-all)"
    else
        required task "Taskfile parse check" || fail=1
    fi
else
    err "no Taskfile.yml generated"
fi

# ── 2. No unrendered Copier variables leaked into output ────────────
# Go-task {{.VAR}} and GitHub Actions ${{ }} are legitimate; copier answer
# variables are not. Check both old-style and v3 custom delimiters.
leaks=$(grep -rEl '\{\{ (project_|author_|organization|repo_url|github_org|current_)|\[\[ (project_|author_|organization|repo_url|github_org|current_)' \
    --exclude-dir=.git . 2>/dev/null || true)
if [ -n "$leaks" ]; then
    err "unrendered template variables found in: ${leaks}"
fi

# ── 3. Rendered workflows are valid (actionlint) ────────────────────
STRICT_WORKFLOWS="${STRICT_WORKFLOWS:-1}"
if [ -d .github/workflows ]; then
    if have actionlint; then
        # Same exclusion the generated Taskfile's lint:actions uses — the
        # project-automation/claude workflows intentionally single-quote
        # GraphQL queries and jq expressions containing '$var'.
        if ! (SHELLCHECK_OPTS="--exclude=SC2016" actionlint); then
            if [ "$STRICT_WORKFLOWS" = "1" ]; then
                err "actionlint failed on rendered workflows"
            else
                echo "WARN: actionlint failed on rendered workflows (non-blocking until template workflows are rewritten)"
            fi
        fi
    else
        required actionlint "workflow lint" || fail=1
    fi
fi

# ── 3b. Rendered JS/TS/JSON is Prettier-clean (node projects) ────────
# A generated repo runs `prettier --check` in its own lint:prettier; if the
# template's RENDERED output isn't already clean, the consumer's very first
# `task verify` fails (recurring example: jinja-bracketed workflow YAML, now
# handed to yamllint via .prettierignore). Catch that here. Explicit options
# match the shipped prettier-config-standard (singleQuote, no-semi,
# trailing-comma none, width 100) so no config package needs installing; the
# rendered .prettierignore (YAML->yamllint, Markdown->markdownlint) is honored.
if [ -f prettier.config.cjs ] && have npx; then
    if ! npx --yes prettier@3 --no-config --single-quote --no-semi \
        --trailing-comma none --print-width 100 --check . >/dev/null 2>&1; then
        err "rendered output is not Prettier-clean — a consumer's first 'task verify' would fail (run: npx prettier --check . in the render)"
    fi
fi

# ── 3c. Rendered Markdown is markdownlint-clean ─────────────────────
# Markdown is excluded from prettier (.prettierignore hands it to markdownlint),
# and nothing else above covers it — so a rendered .md that breaks a markdownlint
# rule (a jinja emitting a bad heading level, list, or fenced block) ships and
# only fails when a consumer runs `task lint:markdown`. Run markdownlint-cli2 in
# CHECK mode with the same globs as that target — NOT `task lint:markdown`, which
# runs `--fix` (it would mutate the render and mask issues). The rendered
# .markdownlint(.json/.jsonc) config is auto-discovered.
if have npx; then
    if ! md_out=$(npx --yes markdownlint-cli2 '**/*.md' '#.claude/**' '#**/node_modules/**' '#dist/**' '#.worktrees/**' '#**/.terraform/**' '#**/.venv/**' '#**/.task/**' 2>&1); then
        printf '%s\n' "$md_out" >&2
        err "rendered Markdown fails markdownlint"
    fi
else
    required npx "rendered Markdown lint (markdownlint-cli2 via npx)" || fail=1
fi

# ── 4. Rendered YAML is valid (yamllint, errors only) ───────────────
if have yamllint; then
    yamllint --no-warnings . || err "yamllint errors in rendered output"
else
    required yamllint "rendered YAML check" || fail=1
fi

# ── 5. Rendered lefthook config parses ──────────────────────────────
if [ -f lefthook.yml ]; then
    if have lefthook; then
        lefthook dump >/dev/null || err "rendered lefthook.yml does not parse"
    else
        required lefthook "lefthook config check" || fail=1
    fi
fi

# ── 6. Rendered shell scripts pass shellcheck + shfmt ────────────────
# .devcontainer only exists when the devcontainer answer is on; a missing dir
# would make `find` (and, via pipefail + set -e, the whole script) fail silently.
shell_dirs="scripts"
[ -d .devcontainer ] && shell_dirs="$shell_dirs .devcontainer"
# shellcheck disable=SC2086
shell_files=$(find $shell_dirs -name '*.sh' -type f 2>/dev/null | tr '\n' ' ')
if [ -n "$shell_files" ]; then
    if have shellcheck; then
        # shellcheck disable=SC2086
        shellcheck --severity=error $shell_files || err "shellcheck failed on rendered scripts"
    else
        required shellcheck "rendered script lint" || fail=1
    fi
    if have shfmt; then
        # shellcheck disable=SC2086
        shfmt -d $shell_files || err "shfmt failed on rendered scripts"
    fi
    # A rendered script with a shebang must ship executable — else the generated
    # repo's lifecycle hooks / `task` callers can't run it, and repos on the
    # legacy node hygiene-check fail their own lint:hygiene on first commit.
    # Safe to check the on-disk bit here: the render lands on the local FS where
    # this test runs (not a fileMode-losing devcontainer mount).
    for sf in $shell_files; do
        [ "$(head -c 2 "$sf" 2>/dev/null)" = "#!" ] || continue
        [ -x "$sf" ] || err "rendered shell script is not executable: $sf"
    done
fi

# ── 7. Rendered JSON files parse (devcontainer.json is JSONC — skipped) ──
json_fail=0
while IFS= read -r jf; do
    case "$jf" in
    *devcontainer.json) continue ;;
    esac
    if ! python3 -c "import json,sys; json.load(open(sys.argv[1]))" "$jf" 2>/dev/null; then
        err "invalid JSON in rendered file: $jf"
        json_fail=1
    fi
done < <(find . -name '*.json' -not -path './.git/*' -not -path './node_modules/*' 2>/dev/null)
[ "$json_fail" -eq 0 ] && echo "JSON: all rendered .json files parse"

# ── 8. Devcontainer configs are readable by the devcontainers CLI ───
if [ -d .devcontainer ]; then
    if ! have devcontainer || ! docker info >/dev/null 2>&1; then
        echo "SKIP: devcontainer CLI or docker daemon unavailable — skipping devcontainer config check"
    else
        for cfg in .devcontainer/devcontainer.json .devcontainer/dev/devcontainer.json; do
            [ -f "$cfg" ] || continue
            devcontainer read-configuration --workspace-folder . --config "$cfg" >/dev/null ||
                err "devcontainer read-configuration failed for $cfg"
        done
    fi
fi

# ── 9. Meta files rendered when enabled ─────────────────────────────
if [ "$profile" = "meta" ]; then
    [ -f ".meta/Code Project - Smoke Test.bunch" ] || err "Bunch file missing from .meta/"
    [ -f ".meta/Smoke Test.md" ] || err "Obsidian note missing from .meta/"
fi

# ── 9b. docs/project-management.md rendered per project_management answer ──
# Two mutually-exclusive conditional-named source files share the rendered name
# docs/project-management.md; assert the right one lands (and none does when the
# answer is 'none') so a broken filename condition can't ship silently.
case "$profile" in
full) # project_management=github; github_org=test-org (an org repo)
    [ -f docs/project-management.md ] || err "GitHub project-management.md missing from docs/"
    grep -q 'Not planned' docs/project-management.md || err "GitHub project-management.md missing expected content"
    # project_management=github → the project-setup script + task render
    # (shellcheck at step 6 and `task --list-all` at step 1 then validate them)
    [ -f scripts/setup-github-project.sh ] || err "scripts/setup-github-project.sh did not render for project_management=github"
    # project_management=github → the repo label-setup script renders
    [ -f scripts/setup-github-labels.sh ] || err "scripts/setup-github-labels.sh did not render for project_management=github"
    # org + github → the org issue-fields + issue-types scripts render too
    [ -f scripts/setup-github-issue-fields.sh ] || err "scripts/setup-github-issue-fields.sh did not render for github+org"
    [ -f scripts/setup-github-issue-types.sh ] || err "org-gated scripts/setup-github-issue-types.sh did not render"
    ;;
meta) # project_management=linear
    [ -f docs/project-management.md ] || err "Linear project-management.md missing from docs/"
    head -1 docs/project-management.md | grep -qx '# Linear' || err "Linear project-management.md not titled 'Linear'"
    grep -q 'TODO' docs/project-management.md || err "Linear project-management.md missing TODO marker"
    [ ! -f scripts/setup-github-labels.sh ] || err "setup-github-labels.sh rendered but project_management!=github for profile '$profile'"
    [ ! -f scripts/setup-github-issue-fields.sh ] || err "setup-github-issue-fields.sh rendered but project_management!=github for profile '$profile'"
    ;;
*) # project_management=none — neither the doc nor the project-setup scripts render
    [ ! -f docs/project-management.md ] || err "docs/project-management.md present but project_management=none for profile '$profile'"
    [ ! -f scripts/setup-github-project.sh ] || err "setup-github-project.sh rendered but project_management=none for profile '$profile'"
    [ ! -f scripts/setup-github-labels.sh ] || err "setup-github-labels.sh rendered but project_management=none for profile '$profile'"
    [ ! -f scripts/setup-github-issue-fields.sh ] || err "setup-github-issue-fields.sh rendered but project_management=none for profile '$profile'"
    [ ! -f scripts/setup-github-issue-types.sh ] || err "org-gated setup-github-issue-types.sh rendered for personal-repo profile '$profile'"
    ;;
esac

# ── 9c. Issue forms: default assignee always renders; the org issue `type:` key
#       is present only on org repos (issue types are org-level) ──
if [ -f .github/ISSUE_TEMPLATE/bug.yml ]; then
    grep -q '^assignees:' .github/ISSUE_TEMPLATE/bug.yml || err "bug.yml is missing the default assignee"
    case "$profile" in
    full) # org repo (github_org != author) → the form declares the org issue type
        grep -q '^type: Bug$' .github/ISSUE_TEMPLATE/bug.yml || err "bug.yml missing 'type: Bug' on an org repo"
        ;;
    *) # personal repo → no org issue types, so the type: key must be absent
        ! grep -q '^type:' .github/ISSUE_TEMPLATE/bug.yml || err "bug.yml has a type: key on a personal repo (org-only)"
        ;;
    esac
fi

# A bare organization is not a valid CODEOWNERS principal. The full profile
# deliberately changes github_org, so this catches regressions where the owner
# default follows the repository organization instead of the human author.
grep -Fxq '* @evanharmon1' .github/CODEOWNERS || err "CODEOWNERS does not default to the human author account"

# ── 9d. skills-sync renders per use_skills_sync ─────────────────────
# General and IaC profiles render with use_skills_sync=false because their
# currently seeded categories are empty; web profiles use the default (on).
# Assert the conditionally-named files + gated tasks appear/disappear together.
case "$profile" in
minimal | iac) # use_skills_sync=false -> none of the machinery renders
    [ ! -f .skills-sync.yaml ] || err ".skills-sync.yaml rendered but use_skills_sync=false"
    [ ! -f scripts/sync-skills.sh ] || err "scripts/sync-skills.sh rendered but use_skills_sync=false"
    ! grep -q 'sync:skills:' Taskfile.yml || err "sync:skills task rendered but use_skills_sync=false"
    ;;
*) # web profiles default on -> manifest, engine, and tasks all present
    [ -f .skills-sync.yaml ] || err ".skills-sync.yaml missing (use_skills_sync default on)"
    [ -x scripts/sync-skills.sh ] || err "scripts/sync-skills.sh missing or not executable"
    grep -q 'sync:skills:' Taskfile.yml || err "sync:skills task missing (use_skills_sync default on)"
    grep -q '^  - universal$' .skills-sync.yaml || err ".skills-sync.yaml categories missing 'universal' (skill_categories default)"
    ;;
esac

# ── 9d2. CodeQL renders only when explicitly selected for a supported stack ──
# The iac profile models a private repo without GitHub Code Security and sets
# use_codeql=false. Full still covers the enabled Terraform/Python + Node matrix.
case "$profile" in
minimal | iac)
    [ ! -f .github/workflows/codeql.yml ] || err "codeql.yml rendered for CodeQL-off profile '$profile'"
    ! grep -q 'workflows/codeql.yml' README.md || err "CodeQL badge rendered for CodeQL-off profile '$profile'"
    ! grep -q 'FULL_SECURITY_SCAN' Taskfile.yml || err "setup:github enables CodeQL for CodeQL-off profile '$profile'"
    ;;
*)
    [ -f .github/workflows/codeql.yml ] || err "codeql.yml missing for CodeQL-enabled profile '$profile'"
    grep -q 'workflows/codeql.yml' README.md || err "CodeQL badge missing for CodeQL-enabled profile '$profile'"
    grep -q 'FULL_SECURITY_SCAN' Taskfile.yml || err "setup:github does not enable selected CodeQL workflow"
    ! grep -q 'continue-on-error: true' .github/workflows/codeql.yml || err "CodeQL analysis is allowed to fail open"
    grep -Fq 'result="${{ needs.analyze.result }}"' .github/workflows/codeql.yml || err "CodeQL aggregate does not inspect the analyze result"
    grep -Fq '[ "$result" != "success" ] && [ "$result" != "skipped" ]' .github/workflows/codeql.yml || err "CodeQL aggregate does not reject analysis failures"
    ;;
esac
if [ "$profile" = "iac" ]; then
    grep -q '^use_codeql: false$' .copier-answers.yml || err "iac fixture did not persist use_codeql=false"
    grep -q 'CodeQL is deliberately omitted' docs/architecture/security.md || err "CodeQL-off security docs do not explain the SAST gap"
fi

# ── 9d3. foreman renders per use_foreman (default off) ──────────────
# Full explicitly enables Foreman; every other profile exercises the safer
# default-off branch. Assert all gated pieces appear/disappear together.
if [ "$profile" != "full" ]; then
    [ ! -d scripts/foreman ] || err "scripts/foreman/ rendered but use_foreman=false"
    [ ! -f taskfiles/foreman.yml ] || err "taskfiles/foreman.yml rendered but use_foreman=false"
    [ ! -f .foreman.toml ] || err ".foreman.toml rendered but use_foreman=false"
    [ ! -d .claude/agents ] || err ".claude/agents rendered but use_foreman=false"
    ! grep -q 'foreman: taskfiles/foreman.yml' Taskfile.yml || err "foreman include rendered but use_foreman=false"
else
    [ -d scripts/foreman ] || err "scripts/foreman/ missing (use_foreman=true)"
    [ -x scripts/foreman/backends/claude.sh ] || err "foreman claude.sh backend missing or not executable"
    [ -x scripts/foreman/backends/mock.sh ] || err "foreman mock.sh backend missing or not executable"
    [ -f taskfiles/foreman.yml ] || err "taskfiles/foreman.yml missing (use_foreman=true)"
    [ -f .foreman.toml ] || err ".foreman.toml missing (use_foreman=true)"
    [ -f .claude/agents/foreman-implementer.md ] || err "foreman agent definitions missing"
    grep -q 'foreman: taskfiles/foreman.yml' Taskfile.yml || err "foreman Taskfile include missing"
    grep -q 'expected_login' .foreman.toml || err ".foreman.toml missing expected_login"
fi

# ── 9e. devcontainer machinery renders per the devcontainer answer ──
# minimal renders with devcontainer=false; every other profile has it on.
# The helper scripts are conditionally named, so a broken gate would either
# ship dead weight into devcontainer=false repos or drop them from real ones.
if [ "$profile" = "minimal" ]; then
    [ ! -d .devcontainer ] || err ".devcontainer/ rendered but devcontainer=false"
    [ ! -f scripts/devcontainer-assert.sh ] || err "scripts/devcontainer-assert.sh rendered but devcontainer=false"
    [ ! -f scripts/devcontainer-smoke.sh ] || err "scripts/devcontainer-smoke.sh rendered but devcontainer=false"
    ! grep -q 'test:devcontainer:permissions:' Taskfile.yml || err "test:devcontainer tasks rendered but devcontainer=false"
else
    [ -d .devcontainer ] || err ".devcontainer/ missing (devcontainer on for profile '$profile')"
    [ -x scripts/devcontainer-assert.sh ] || err "scripts/devcontainer-assert.sh missing or not executable"
    [ -x scripts/devcontainer-smoke.sh ] || err "scripts/devcontainer-smoke.sh missing or not executable"
fi

# ── 9f. .prettierignore: web-app-only entries are gated by project type ──
# TanStack/Convex ignores (routeTree.gen.ts, convex/_generated, .convex) must
# render for web-app and must NOT leak into other node project types.
if [ -f .prettierignore ]; then
    if [ "$profile" = "webapp" ] || [ "$profile" = "meta" ]; then # project_type=web-app
        grep -q 'convex/_generated/' .prettierignore || err ".prettierignore missing web-app entries (convex/_generated) for project_type=web-app"
        grep -q 'src/routeTree.gen.ts' .prettierignore || err ".prettierignore missing web-app entries (routeTree.gen.ts) for project_type=web-app"
    else
        ! grep -q 'convex\|routeTree' .prettierignore || err ".prettierignore leaks web-app-only entries into profile '$profile'"
    fi
fi

# ── 9g. Python CI fails closed on a stale committed lockfile ─────────
# `uv --frozen` deliberately skips the project-metadata freshness check. A
# security audit must instead reject a uv.lock that no longer matches
# pyproject.toml, while a freshly scaffolded repo with no lock may still resolve
# its initial environment.
if [ -f scripts/python-audit.sh ]; then
    grep -q -- '--locked' scripts/python-audit.sh || err "python-audit.sh does not require a current uv.lock"
    ! grep -q -- '--frozen' scripts/python-audit.sh || err "python-audit.sh accepts a potentially stale uv.lock"
    grep -q 'uv sync --locked' .github/workflows/build.yml || err "Python CI sync can silently rewrite a stale uv.lock"
fi

# ── 9h. Terraform has a stable required gate and applies its exact saved plan
ruleset='.github/Branch Protection Ruleset - Protect Main.json'
if [ -f .github/workflows/terraform.yml ]; then
    [ -x scripts/terraform-ci.sh ] || err "Terraform CI helper missing or not executable"
    [ -x scripts/terraform-changed.sh ] || err "Terraform change detector missing or not executable"
    [ -x scripts/test-terraform-ci.sh ] || err "Terraform CI regression missing or not executable"
    grep -q '^  merge_group:$' .github/workflows/terraform.yml || err "Terraform required check cannot run in merge queue"
    ! grep -q '^    paths:$' .github/workflows/terraform.yml || err "required Terraform workflow is suppressed by path filters"
    grep -q 'Invalid Terraform change output' .github/workflows/terraform.yml || err "Terraform aggregate accepts a missing change decision"
    grep -q 'needs: \[changes, terraform-validate\]' .github/workflows/terraform.yml || err "Terraform apply can outrun validation"
    grep -q '"context": "terraform-verify"' "$ruleset" || err "ruleset does not require terraform-verify"
    grep -q '^  terraform:ci:apply:$' Taskfile.yml || err "Terraform apply is not isolated as a CI-only task"
    grep -q 'Refusing Terraform CI apply outside GitHub Actions' scripts/terraform-ci.sh || err "Terraform CI apply lacks its local-mutation guard"
    grep -q -- '-lockfile=readonly' scripts/terraform-ci.sh || err "Terraform CI can rewrite a committed provider lock"
    grep -q -- '-out="$plan_file"' scripts/terraform-ci.sh || err "Terraform apply has no saved review artifact"
    ! grep -Eq '/tmp/tf(plan|converge)|-lock=false' scripts/terraform-ci.sh .github/workflows/terraform.yml || err "Terraform CI retains unsafe shared artifacts or disabled state locking"
    ./scripts/test-terraform-ci.sh || err "Terraform saved-plan regression failed"
else
    [ ! -f scripts/terraform-ci.sh ] || err "Terraform helper rendered when include_terraform=false"
    [ ! -f scripts/terraform-changed.sh ] || err "Terraform change detector rendered when include_terraform=false"
    [ ! -f scripts/test-terraform-ci.sh ] || err "Terraform regression rendered when include_terraform=false"
    ! grep -q '"context": "terraform-verify"' "$ruleset" || err "ruleset requires Terraform for a non-Terraform repo"
fi

# ── 10. No secrets in the rendered tree (gitleaks) ──────────────────
if have gitleaks; then
    gitleaks detect --no-banner --redact --no-git --source . || err "gitleaks findings in rendered output"
else
    required gitleaks "secrets scan" || fail=1
fi

# ── 11. web-astro: the shipped toolchain works on a real Astro app ───
# The render ships eslint.config.js + prettier.config.cjs (with prettier-plugin-astro)
# but no app, so nothing above exercises them. Overlay a minimal Astro fixture
# (package.json + a few src files), install, and run the SHIPPED toolchain against
# it -- a broken config, plugin-API bump, or build regression fails HERE instead of
# in every generated site. Tools run via their binaries (not `task check`) so the
# intentionally-unbuilt esbuild/sharp scripts don't gate them and local plugins
# (eslint-plugin-astro, prettier-plugin-astro) resolve.
if [ "$profile" = "web" ] && [ -f eslint.config.js ]; then
    if ! have pnpm; then
        required pnpm "web-astro toolchain validation" || fail=1
    else
        cp -R "$repo_root/tests/fixtures/web-astro/." .
        pnpm install --silent >/dev/null 2>&1 || true
        bin="node_modules/.bin"
        if [ ! -x "$bin/eslint" ] || [ ! -x "$bin/prettier" ] || [ ! -x "$bin/astro" ]; then
            err "web-astro fixture: install did not provide the toolchain (see tests/fixtures/web-astro/package.json)"
        elif ! "$bin/eslint" . >/dev/null 2>&1; then
            "$bin/eslint" . || true
            err "web-astro fixture: ESLint failed"
        elif ! "$bin/prettier" --check . >/dev/null 2>&1; then
            "$bin/prettier" --check . || true
            err "web-astro fixture: prettier --check failed (prettier-plugin-astro)"
        elif ! "$bin/astro" check >/dev/null 2>&1; then
            "$bin/astro" check || true
            err "web-astro fixture: astro check (typecheck) failed"
        elif ! "$bin/astro" build >/dev/null 2>&1; then
            "$bin/astro" build || true
            err "web-astro fixture: astro build failed"
        else
            echo "web-astro: shipped toolchain (ESLint + Prettier/astro + astro check + build) clean on a real app"
        fi
    fi
fi

# ── 12. web-app: the shipped ESLint config + tsc type-check a real React app ──
# Same idea as the web-astro check above, for the web-app (React) project type.
# The shipped config is ESLint 10 + type-aware linting (projectService), so the
# fixture mirrors a real app: src/routeTree.gen.ts (a codegen stand-in) registers
# the '/' route so createFileRoute type-checks, and convex/ carries its own
# tsconfig + _generated stubs — under projectService every linted TS file must
# belong to a project. The tsc steps guard that the shipped tests/a11y.spec.ts
# and the convex/ functions type-check with their devDeps installed.
if [ "$profile" = "webapp" ] && [ -f eslint.config.js ]; then
    if have pnpm; then
        cp -R "$repo_root/tests/fixtures/web-app/." .
        pnpm install --silent >/dev/null 2>&1 || true
        bin="node_modules/.bin"
        if [ ! -x "$bin/eslint" ] || [ ! -x "$bin/tsc" ]; then
            err "web-app fixture: install did not provide the toolchain (see tests/fixtures/web-app/package.json)"
        elif ! "$bin/eslint" . >/dev/null 2>&1; then
            "$bin/eslint" . || true
            err "web-app fixture: shipped eslint.config.js failed to lint a real React app"
        elif ! "$bin/tsc" --noEmit >/dev/null 2>&1; then
            "$bin/tsc" --noEmit || true
            err "web-app fixture: tsc --noEmit failed — the shipped tests/a11y.spec.ts must type-check with @playwright/test + @axe-core/playwright installed"
        elif ! "$bin/tsc" -p convex --noEmit >/dev/null 2>&1; then
            "$bin/tsc" -p convex --noEmit || true
            err "web-app fixture: tsc -p convex --noEmit failed — the convex/ functions must type-check under their own tsconfig"
        else
            echo "web-app: shipped ESLint + tsc type-check (root + convex) clean on a real React app"
        fi
    else
        required pnpm "web-app toolchain validation" || fail=1
    fi
fi

if [ "$fail" -ne 0 ]; then
    echo "test-template (${profile}): FAILED" >&2
    exit 1
fi
echo "test-template (${profile}): PASS"
