#!/usr/bin/env bash
# test-registry-docs.sh — GATE the human-facing agent-registry tables in
# docs/project-management.md against the machine-readable registry.
#
# ADR 0005 D10 makes that document the human authority for the agent
# vocabulary, and D11 says the registry has executable teeth. A markdown table
# maintained by hand satisfies neither: it drifts the moment a family or
# harness is added, and nothing fails. So the tables are GENERATED —
# `node scripts/agent-registry-labels.mjs docs-tables` — and pasted between
# markers, and this check regenerates them and fails on any difference.
#
#   <!-- registry-tables:begin -->
#   ...generated tables...
#   <!-- registry-tables:end -->
#
# Two modes, decided by whether `template/docs/` exists:
#
#   TEMPLATE repository — both layers are REQUIRED: the root dogfood copy
#     docs/project-management.md and the jinja twin that ships it. The twin is
#     deliberately covered here rather than by the dogfood checks:
#     test-dogfood-parity.sh skips it (it is a .jinja file) and
#     test-dogfood-structure.sh SKIPs docs/project-management.md outright (its
#     root copy is not a render of the template copy), so without this the
#     generated tables could ship stale to every consumer while the root copy
#     stayed current. The registry itself is a verbatim twin, so both layers
#     render byte-identical tables and one expected value serves both.
#
#   GENERATED repository — the document is required when the repo was rendered
#     with `project_management: github`, and only then. The `linear` and `none`
#     answers render a different document at the same path, or none at all.
#
# A MISSING expected document is a failure, never a skip: the whole point of
# the gate is that the published tables cannot silently stop existing.
#
# Usage: test-registry-docs.sh [--answers-file <name>] [registry-path]
#
# --answers-file names Copier's answers file, whose name is configurable
# (`_copier_conf.answers_file`) — the generated Taskfile passes the configured
# one so a repository copied with `--answers-file custom.yml` still resolves
# its tracker. It is a flag rather than a jinja variable because this script is
# a verbatim root<->template twin: it must be byte-identical in both layers,
# so the layer-specific value has to arrive at runtime.
#
# To fix a drift failure: regenerate and paste the block, keeping the markers.
set -euo pipefail

repo="$(git rev-parse --show-toplevel)"
cd "$repo"

answers_file=""
registry=""
while [ "$#" -gt 0 ]; do
    case "$1" in
    --answers-file)
        if [ "$#" -lt 2 ]; then
            echo "TEST FAIL: --answers-file needs a value" >&2
            exit 2
        fi
        answers_file="$2"
        shift 2
        ;;
    --answers-file=*)
        answers_file="${1#*=}"
        shift
        ;;
    -*)
        echo "TEST FAIL: unknown argument: $1" >&2
        exit 2
        ;;
    *)
        registry="$1"
        shift
        ;;
    esac
done

registry="${registry:-agent-registry.json}"
renderer="scripts/agent-registry-labels.mjs"
doc="docs/project-management.md"
begin='<!-- registry-tables:begin -->'
end='<!-- registry-tables:end -->'

for required in "$registry" "$renderer"; do
    [ -f "$required" ] || {
        echo "TEST FAIL: missing required registry asset: $required" >&2
        exit 1
    }
done
command -v node >/dev/null 2>&1 || {
    echo "TEST FAIL: node is required to render the registry documentation tables" >&2
    exit 1
}

expected="$(node "$renderer" docs-tables "$registry")"

# The jinja twin, matched on the `github` in its conditional filename so the
# `linear` variant — a different tracker, with no label taxonomy and no
# registry tables — is never swept in.
twin=""
for candidate in template/docs/*project-management.md*.jinja; do
    [ -f "$candidate" ] || continue
    case "$candidate" in
    *github*) twin="$candidate" ;;
    esac
done

targets=""
if [ -d template/docs ]; then
    # ── template repository ────────────────────────────────────────────
    if [ -z "$twin" ]; then
        echo "TEST FAIL: no GitHub project-management twin under template/docs/ — the document that ships the generated registry tables is gone" >&2
        exit 1
    fi
    if [ ! -f "$doc" ]; then
        echo "TEST FAIL: $doc is missing — the root layer must dogfood the document it ships" >&2
        exit 1
    fi
    targets="$doc
$twin
"
else
    # ── generated repository ───────────────────────────────────────────
    # Which document Copier rendered at $doc is decided by the
    # project_management answer, so read the answer rather than sniffing the
    # document's prose. Prefer the configured answers-file name, then Copier's
    # defaults; if the answer cannot be read either way, fall back to the
    # scripts/setup-github-project.sh file, which is generated by exactly the
    # same condition.
    tracker=""
    for candidate in "$answers_file" .copier-answers.yml .copier-answers.yaml; do
        [ -n "$candidate" ] || continue
        [ -f "$candidate" ] || continue
        tracker="$(sed -n 's/^project_management:[[:space:]]*//p' "$candidate" |
            tr -d "\"'" | head -n1)"
        if [ -n "$tracker" ]; then break; fi
    done
    if [ -z "$tracker" ]; then
        if [ -f scripts/setup-github-project.sh ]; then
            tracker="github"
        else
            tracker="none"
        fi
        echo "note: no project_management answer found; inferred '$tracker' from scripts/setup-github-project.sh" >&2
    fi

    if [ "$tracker" != "github" ]; then
        echo "test-registry-docs: skipping — project_management=$tracker renders no GitHub Projects document."
        exit 0
    fi
    if [ ! -f "$doc" ]; then
        echo "TEST FAIL: $doc is missing but project_management=github — the published registry tables are gone" >&2
        exit 1
    fi
    targets="$doc
"
fi

fails=0
checked=0
while IFS= read -r target; do
    [ -n "$target" ] || continue
    checked=$((checked + 1))

    # Exactly one marker pair. Zero means the block was dropped (or never
    # added); more than one means an ambiguous region this check cannot
    # regenerate deterministically.
    begins="$(grep -cxF "$begin" "$target" || true)"
    ends="$(grep -cxF "$end" "$target" || true)"
    if [ "$begins" != 1 ] || [ "$ends" != 1 ]; then
        echo "FAIL: $target must contain exactly one '$begin' line and one '$end' line (found $begins and $ends)" >&2
        fails=$((fails + 1))
        continue
    fi

    actual="$(awk -v b="$begin" -v e="$end" '
        $0 == b { inside = 1; next }
        $0 == e { inside = 0 }
        inside' "$target")"

    if [ "$actual" != "$expected" ]; then
        echo "FAIL: the registry tables in $target do not match agent-registry.json:" >&2
        diff -u <(printf '%s\n' "$actual") <(printf '%s\n' "$expected") >&2 || true
        fails=$((fails + 1))
    fi
done <<EOF
$targets
EOF

if [ "$fails" -ne 0 ]; then
    echo "test-registry-docs: $fails document(s) drifted from agent-registry.json." >&2
    echo "Regenerate with: node $renderer docs-tables $registry" >&2
    echo "and replace the lines between the markers, in every layer that carries them." >&2
    exit 1
fi

echo "test-registry-docs: registry tables in $checked document(s) match agent-registry.json."
